### PR TITLE
Fix ksobjc_objectType error

### PR DESCRIPTION
**Pull request by xuezhulian**
NSObject *obj = [NSObject new];
ksobjc_objectType((__bridge void *)obj);

Both object and block return KSObjCTypeUnknown.

### CODE REVIEW

**Review by GLinnik21 — APPROVED** [review]

**Comment by GLinnik21** [comment]
Shouldn't be `Source/KSCrash-Tests/KSObjC_Tests.m` fixes as well?

**Comment by xuezhulian** [comment]
KSObjC_Tests does not need to be modified, all the units start with testObjectType have passed.

**Comment by GLinnik21** [comment]
@bamx23 should we merge to `master` or move to `release-2.0`?

**Comment by bamx23** [comment]
Let's merge to `master` and update `release-2.0` from it

**Pull request merged**
