### PR TITLE
Share WatchOS scheme and fix umbrella warnings

### PR DESCRIPTION
**Pull request by joshdholtz**
- Sharing WatchOS scheme to allow for Carthage building of WatchOS framework
- Added files to module map to silence some umbrella warnings
- Removed a unicode character in a while

### CODE REVIEW

**Comment by kstenerud** [comment]
Cool! Thanks!

**Comment by joshdholtz** [comment]
Not a problem! Glad to be of service again 😊

**Comment by joshdholtz** [comment]
Haven't talked in a while but hope all is well!

**Comment by joshdholtz** [comment]
@kstenerud Oh, could you also pop a `1.15.4` on GitHub of that whenever you get a chance? 😊 This _shouldn't_ need a CocoaPods push since CocoaPods doesn't use these targets anyway... Just need the GitHub release for Carthage

**Pull request merged**
