### PR TITLE
Move install path to config

### PR DESCRIPTION
**Pull request by bamx23**
This simplifies logic and makes API more consistent. Yes, indeed #513 had this suggetion. So consider this is a follow up.

### CODE REVIEW

**Comment by GLinnik21** [comment]
Linked #513

**Review by GLinnik21 — APPROVED** [review]
It looks good so far, but I'm just wondering what this might affect. It seems like getting reports isn't affected because KSCrash doesn't allow you to get them without activation, right?

**Comment by GLinnik21** [comment]
Will this change also make it impossible to implement the "get reports without activation" feature in the future?

**Comment by bamx23** [comment]
> Will this change also make it impossible to implement the "get reports without activation" feature in the future?

No, there are 2 options: allow pre-installation without monitors or introduce a separate "install reporting" method.

**Pull request merged**
